### ISSUE TITLE
Allow customization of flowchart icons

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1148]
A more strict version based off of this idea here: https://github.com/kedro-org/kedro-viz/issues/480

**Comment by tynandebold** [comment]
See @NeroOkwa's [comment](https://github.com/kedro-org/kedro-viz/issues/480#issuecomment-1327747457) in #480 for more context.

**Comment by datajoely** [comment]
If we were to make the following open-source icon libraries available to users that would be incredible:

https://simpleicons.org/
https://pictogrammers.com/

- We could could do defaults for things like Pandas, CSV etc.
- But the exciting possibility would be if we could allow the user (via factories as well 🚀 ) to do this sort of thing

```yaml
my_dataset:
   type: my.custom.dataset
   path: ...
   kedro-viz:
      layer: primary
+     icon: mdi/Bank        #example 1
+     icon: simple/kedro    #example 2
```

References:
> [mdi/Bank](https://pictogrammers.com/library/mdi/icon/bank/)
> [simple/kedro](https://simpleicons.org/?q=kedro)

**Comment by astrojuanlu** [comment]
or rather, something like

```
my_dataset:
  type: ...
  metadata:
    kedro-viz:
      style:
        icon: mdi/Bank
```

with `style` including other coloring properties (see #1706)
