### ISSUE TITLE
Improve Backend Unit test execution on CI

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1805]
## Description

Improve CI execution time for backend unit tests which should not rely on building the react application, rather depend only on backend functions.

## Context

When we are running unit_tests on CircleCI, during build_backend we have the following steps -

```yml
unit_tests:
    parameters:
      python_version:
        type: string
    executor:
      name: docker
      python_version: <<parameters.python_version>>
    steps:
      - setup
      - run:
          name: Run Python tests
          command: make pytest
```

The `setup` step has -
```yml
  setup:
    steps:
      - checkout
      - setup_python_env
      - install_node_dependencies
      - npm_build
```

- Apart from Installing Python dependencies which takes (>3m) , Build React application takes (>2m).
- We need to refactor our unit tests if needed to test only python functions and do not depend on building react application
- Building the react app should only be part of frontend tests and e2e tests.

## Possible Implementation

- Remove all frontend build steps (Install Node.js -> Build React application)
- Refactor pytests to rely only on python env and backend functions 

## Checklist

- [x] Include labels so that we can categorise your feature request
